# Generated by Django 5.1.3 on 2024-11-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='data_nasc',
            new_name='dt_nasc',
        ),
    ]
